import Head from 'next/head'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>HooBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lets build a portfolio</h1>
    </div>
  )
}
