import Head from 'next/head'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>HooBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl text-red-400 font-bold">Hello HooBank</h1>
    </div>
  )
}
